### ISSUE TITLE
Encountered problem downloading/extracting https://dev.azure.com/Git-for-Windows/.....?artifactName=git-sdk-64-build-installers&api-version=7.0&%24format=zip

### ISSUE THREAD

**Issue by michkot** [git-for-windows/setup-git-for-windows-sdk#336]
(Hi, thanks for all the efforts!)

I am trying to build installer for my patched version of git-for-windows (untracked cache fix), but it seems the action is now failing on the point where it interacts with the action from ref v0 from this repository.

https://github.com/michkot/git/runs/5835168717?check_suite_focus=true

> Encountered problem downloading/extracting https://dev.azure.com/Git-for-Windows/f3317b6a-fa67-40d4-9a33-b652e06943df/_apis/build/builds/97203/artifacts?artifactName=git-sdk-64-build-installers&api-version=7.0&%24format=zip: Error: unexpected end of file; Retrying in 32 seconds...

I've tried to re-run, but the same issue occurs.

Now I am trying with v1, (different installer, right?), to see if the problem would be the same - still running: https://github.com/michkot/git/runs/5836877048

**Comment by dscho** [comment]
Looks like this might be a bug introduced in a recent version. The error message is produced [here](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/926836bd4684a48ea52fd4a9abf08d01ed9688f5/src/downloader.ts#L278), but there must be something throwing the "unexpected end of file" exception within that `try { ... } catch` block.

**Comment by dscho** [comment]
I'm a bit time-constrained, do you think you could debug this a bit further?

**Comment by michkot** [comment]
Okey, thanks for the hints. It seems there is a newer artifact on azure:
https://dev.azure.com/Git-for-Windows/f3317b6a-fa67-40d4-9a33-b652e06943df/_apis/build/Builds/97426/artifacts

I've launched nother github action:https://github.com/michkot/git/runs/5867410889?check_suite_focus=true will see if it makes any difference.

I've also tried to download the previous artifact locally and extract it - it took a while to download it, but there were no problems (using 7zip).

**Comment by michkot** [comment]
Okey it still fails. Wild guess - maybe there is not enough space on the github action VM to accommodate the 300MB zip and ~900MB extracted data?

**Comment by dscho** [comment]
> maybe there is not enough space on the github action VM to accommodate the 300MB zip and ~900MB extracted data?

Quite possible.

Hmm.

Maybe we need to make use of the fact that GitHub Actions' Windows build agents have a copy of Git for Windows and can therefore use the `unzip` and `tar` executables, e.g. via `git -c 'alias.unzip=!unzip' unzip [<args>]`? That way, the data flows to processes other than the node.js one that runs the Action.

**Comment by michkot** [comment]
I checked the specs and there should be gigabytes of space available on the machine - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners.

It seems it's failing exactly at the end of the file actually:
the artifacts contains "32 153" files and "2 756" folders. The error occurs after "31 250 items" are extracted... Maybe the node process can not handle the stream length? Hard to say :( 

If I have some time to play around, I'll take a look at running the nodejs code locally next week, but ... will see.

**Comment by dscho** [comment]
> If I have some time to play around, I'll take a look at running the nodejs code locally next week, but ... will see.

Excellent. FWIW if I were to play around with this, I would set up a Sandbox Pipeline that creates a tiny Pipeline Artifact that looks similar to the one we're trying to download and extract here, then hard-code that build in a debug branch. Unfortunately, I will be mostly offline for the next ten days, therefore I won't have time to do that.

**Comment by dscho** [comment]
I finally got some time to play with it a bit more. Looks like the `build-installers` artifact can be obtained relatively quickly by simply performing a shallow, bare clone and generating it from scratch: it takes [2 minutes and 11 seconds in a test run](https://github.com/dscho/setup-git-for-windows-sdk/runs/6818794662?check_suite_focus=true#step:2:1), which is in line with what the `ci-artifacts` run [takes for the same task](https://github.com/git-for-windows/git-sdk-64/runs/6786679678?check_suite_focus=true#step:4:1).

Note: In [`git-sdk-64-extra-artifacts`](https://dev.azure.com/git-for-windows/git/_build?definitionId=29&_a=summary), we seem to build the `minimal-sdk` first, only so that we can use it to build the `build-installers` artifact. The build definition has this comment about it:

```
# Use the just-created minimal-sdk artifact to run the script
#
# This is needed because Git for Windows might have a different `msys-2.0.dll`
# version, one that is incompatible with the one from the SDK, which we
# however need to run in build-installers because  `make-file-list.sh` needs access
# to Pacman.
```

However, the [`ci-artifacts` workflow](https://github.com/git-for-windows/git-sdk-64/actions/runs/2458948166/workflow) does no such thing and seems to run fine. It actually [uses a partial clone](https://github.com/git-for-windows/git-sdk-64/actions/runs/2458948166/workflow#L21), which we should do in `setup-git-for-windows-sdk`, too.

**Comment by dscho** [comment]
So... I think I have something that will work: https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/384

**Comment by dscho** [comment]
I'll call this closed. @michkot thank you for your patience, I am confident that we addressed this issue and at the same time made the whole setup more robust. Would you mind testing to confirm?

**Comment by michkot** [comment]
Hi! I noticed the updates but was busy! I will check what changed and test it out tomorrow!
