### ISSUE TITLE
Self-hosted runner: `C:/git-sdk-64-full' already exists`

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/setup-git-for-windows-sdk#398]
On a self-hosted runner, when running this action for the second time, it fails with the following error:

```
Downloading git-sdk-64-full
Cloning git-sdk-64
  Notice: Cloning https://github.com/git-for-windows/git-sdk-64 to .tmp
  Cloning into bare repository '.tmp'...
Checking out git-sdk-64
  Preparing worktree (detached HEAD 456de1018)
  fatal: 'C:/git-sdk-64-full' already exists
Error: process exited with code [12](https://github.com/dennisameling/git/runs/7046758549?check_suite_focus=true#step:3:13)8
```

This is because, unlike GitHub-hosted runners, self-hosted runners can reuse the filesystem on the machine. It would probably be good to update this Action to either:
- Respect the already installed `git-sdk-64-full` and reuse it (and probably update it to the latest commit)
- Remove the existing `git-sdk-64-full` (e.g. by adding a `force` input to the Action) and redownload

If you could let me know what your preference is, I'm happy to update the Action accordingly. Thanks!

Example run here: https://github.com/dennisameling/git/runs/7046758549?check_suite_focus=true

**Comment by dscho** [comment]
The problem with "updating to the newest commit" is that we don't have enough information to do that, it's long gone by that time.

The safer thing would be to put the SDK into a worktree-local path that gets automatically cleaned up.
