### ISSUE TITLE
Error: spawn C:/Program Files/Git/cmd/git.exe ENOENT

### ISSUE THREAD

**Issue by AllanOricil** [git-for-windows/setup-git-for-windows-sdk#472]
It fails while cloning git installer repo:

![image](https://user-images.githubusercontent.com/55927613/189106972-84114c35-b7ab-4640-b925-22302310b40b.png)

**Comment by dscho** [comment]
Is this with a self-hosted runner?

**Comment by AllanOricil** [comment]
@dscho yes, it is

**Comment by dscho** [comment]
@AllanOricil could you validate that the proposed fix works for you? You can test via:

```yml
- uses: git-for-windows/setup-git-for-windows-sdk@9baeb2224d0028f3a5a7a0cf7fed52f1b2e509c4
[...]
```

**Comment by AllanOricil** [comment]
Next week I can try again

**Comment by dscho** [comment]
> Next week I can try again

Thank you. I will wait with merging that PR before you confirm that it works.

**Comment by dscho** [comment]
> Next week I can try again

The week is almost over... 😁

**Comment by AllanOricil** [comment]
@dscho sorry. Im also handling other problem at work. Had to do a demo this week. But don't worry. Im going to do it today for sure!

**Comment by AllanOricil** [comment]
Sorry. Didnt have time to do run a test. Will try again today.
