### ISSUE TITLE
 Error: spawn C:/Program Files/Git/cmd/git.exe ENOENT 

### ISSUE THREAD

**Issue by cmilea38** [git-for-windows/setup-git-for-windows-sdk#777]
Hi there,

Really appreaciate if this will work.

I saw an issue very similar to this closed last year, but it is still happening to my setup.

I have a self-hosted runner, running on windows-latest using the following steps:

```

 steps:
    - uses: actions/checkout@v4   
      with:
       fetch-depth: '0'      
       run: |
        npm install
        npm test
      name: Install node
    - uses: actions/setup-node@v4
      with:
         node-version: 18
    - name: Setup Git for Windows' minimal SDK
      uses: git-for-windows/setup-git-for-windows-sdk@v1  
      with:
        flavor: full
    - name: Build
      shell: bash
      run: make

``` 

  

- the output for node install is:

``` 
`Environment details
  node: v18.18.2
  npm: 9.8.1
  yarn: 
  ::endgroup::`

``` 

but the  Setup Git for Windows' minimal SDK step fails with the following:

``` 


`##[debug]Evaluating condition for step: 'Setup Git for Windows' minimal SDK'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Setup Git for Windows' minimal SDK
##[debug]Register post job cleanup for action: git-for-windows/setup-git-for-windows-sdk@v1
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run git-for-windows/setup-git-for-windows-sdk@v1
  with:
    flavor: full
    architecture: x86_64
    msys: false
    cleanup: false
    verbose: [2](https://github.com/MYREPOs/actions/runs/6874340462/job/18695842017#step:4:2)50
    cache: auto
    github-token: ***
  env:
    ENVIRONMENT: DV
    APPLICATION: DBConnector
Got commit 5df5f255fb75fc80[4](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:4)9009cd4cf[5](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:5)92b74dfb4ffc7 for git-sdk-[6](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:6)4
Found a fast, temporary disk on this VM (D:/). Will use that.
Downloading git-sdk-64-full
::group::Cloning git-sdk-64
Cloning git-sdk-64
  Cloning https://github.com/git-for-windows/git-sdk-64 to .tmp
  Error: spawn C:/Program Files/Git/cmd/git.exe ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:2[8](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:8)6:1[9](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:9))
      at onErrorNT (node:internal/child_process:484:[16](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:16))
      at processTicksAndRejections (node:internal/process/task_queues:82:[21](https://github.com/MYREPO/actions/runs/6874340462/job/18695842017#step:4:21))
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Save intra-action state isPost = true
  ##[debug]Finishing: Setup Git for Windows' minimal SDK`


``` 

Any advice would be really appreciated, thank you!

**Comment by dscho** [comment]
> Error: spawn C:/Program Files/Git/cmd/git.exe ENOENT

This means that Git for Windows is not installed.

However, obviously the build agent needs to come with a copy of Git. The Action could look for that as a fall-back. You will need to log into your self-hosted runner and see whether there is any obvious path (probably relative to [`runner.tool_cache`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context)) that can be used.

Once you have that path, you will have to change this code: https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/44e6ddb49b3d0702122b5caa42530aa71828fd1a/src/git.ts#L7-L15

As you can see, there is already handling for the `externals/git` directory, if it exists. Obviously it does not exist in your setup, so you will have to figure out a different location where `git.exe` is present. Without `git.exe`, this Action cannot work.

Hopefully you can figure this all out and test it by using your own fork (something like `uses: cmilea38/setup-git-for-windows-sdk@your-branch-name`, you will need to commit your local changes, then run `npm run build && npm run package`, commit again, and push the branch to your fork), then open a PR to fix this once and for all.

**Comment by dscho** [comment]
@cmilea38 any updates?
